2021-04-15 21:49:52,304 ERROR: Exception on /user/kavvadias [GET] [in /home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kavvadias/Projects/flask-mega/app/routes.py", line 92, in user
    return render_template('user.html', user=user, posts=posts, form=form,
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/kavvadias/Projects/flask-mega/app/templates/user.html", line 45, in template
    {% next_url %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'next_url'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-04-15 21:51:04,303 INFO: Microblog startup [in /home/kavvadias/Projects/flask-mega/app/__init__.py:44]
2021-04-15 21:51:05,353 ERROR: Exception on /user/kavvadias [GET] [in /home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kavvadias/Projects/flask-mega/app/routes.py", line 92, in user
    return render_template('user.html', user=user, posts=posts, form=form,
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/kavvadias/Projects/flask-mega/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kavvadias/Projects/flask-mega/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/kavvadias/Projects/flask-mega/app/templates/user.html", line 39, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2021-04-15 21:51:07,965 ERROR: Exception on /user/kavvadias [GET] [in /home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kavvadias/Projects/flask-mega/app/routes.py", line 92, in user
    return render_template('user.html', user=user, posts=posts, form=form,
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/kavvadias/Projects/flask-mega/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/kavvadias/Projects/flask-mega/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kavvadias/Projects/flask-mega/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/kavvadias/Projects/flask-mega/app/templates/user.html", line 39, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2021-04-15 21:54:35,082 INFO: Microblog startup [in /home/kavvadias/Projects/flask-mega/app/__init__.py:44]
